# Generated by Django 2.2.4 on 2021-03-23 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tv_shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='releasedate',
            field=models.DateField(max_length=255),
        ),
    ]
