# Generated by Django 2.2.4 on 2021-03-24 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tv_shows', '0002_auto_20210323_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='desc',
            field=models.TextField(default='No blurb yet.'),
            preserve_default=False,
        ),
    ]
